services:
  portfolio:
    image: nginx:alpine
    container_name: portfolio
    ports:
      - "90:80"
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
    networks:
      - portfolio

networks:
  portfolio:
    name: portfolio
    driver: bridge