services:
  portfolio:
    image: portfolio:latest
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:80"
    restart: unless-stopped
    networks:
      - portfolio

networks:
  portfolio:
    name: portfolio
    driver: bridge